### ISSUE TITLE
got an unexpected keyword argument 'force_TA_refresh'

### ISSUE THREAD

**Issue by mrgreedy911** [Drakkar-Software/OctoBot#415] opened 2018-10-02 23:16 UTC
## Step 2: Describe your environment
  * OS : [Windows, Ubuntu, Debian, Raspbian...] 
Windows 10
  * Python Version: _____ (`python -V`)
Python 3.6
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**
When adding an Real time analysis i get this error
InstantFluctuationsEvaluator

Is it an issue with the exchange?
**Expected behavior**

### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 

2018-10-03 01:09:40 | ERROR | InstantFluctuationsEvaluator | Exception in eval_impl(): notify_evaluator_thread_managers() got an unexpected keyword argument 'force_TA_refresh'
-- | -- | -- | --

```
2018-10-03 01:09:58 ERROR  SymbolTimeFramesDataUpdaterThread logging_util.py:46        when refreshing data for time frame TimeFrames.ONE_DAY for XEM/BTC: bittrex GET https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=day&marketName=BTC-XEM HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)
2018-10-03 01:09:58 ERROR  SymbolTimeFramesDataUpdaterThread logging_util.py:50       bittrex GET https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=day&marketName=BTC-XEM HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 383, in _make_request
  File "http\client.py", line 1331, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
  File "site-packages\urllib3\contrib\pyopenssl.py", line 294, in recv_into
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 445, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 357, in increment
  File "site-packages\urllib3\packages\six.py", line 686, in reraise
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 389, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\ccxt\base\exchange.py", line 378, in fetch
  File "site-packages\requests\sessions.py", line 512, in request
  File "site-packages\requests\sessions.py", line 622, in send
  File "site-packages\requests\adapters.py", line 526, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluator\Updaters\symbol_time_frames_updater.py", line 65, in _execute_update
  File "evaluator\Updaters\symbol_time_frames_updater.py", line 39, in _refresh_data
  File "trading\exchanges\exchange_dispatcher.py", line 76, in get_symbol_prices
  File "trading\exchanges\rest_exchanges\rest_exchange.py", line 140, in get_symbol_prices
  File "site-packages\ccxt\bittrex.py", line 441, in fetch_ohlcv
  File "site-packages\ccxt\bittrex.py", line 761, in request
  File "site-packages\ccxt\base\exchange.py", line 324, in fetch2
  File "site-packages\ccxt\base\exchange.py", line 388, in fetch
  File "site-packages\ccxt\base\exchange.py", line 309, in raise_error
```

**Comment by mrgreedy911** [comment] 2018-10-02 23:44
http://prntscr.com/l1h00u 
these time frames are supported by bittrex, is it possible to config this ?

**Comment by Herklos** [comment] 2018-10-03 08:55
Hello mrgreedy911,

Actually it's strongly advised to use RealTime evaluators with a WebSocket. 
Currently Octobot has only one WS for Binance. 
You can follow WS developments on [this page](https://github.com/Drakkar-Software/OctoBot/wiki/Exchanges).

For you issue, its seems that your OctoBot lost connection with bittrex, it may require a WS.

**Comment by Herklos** [comment] 2018-10-03 08:57
> 
> 
> http://prntscr.com/l1h00u
> these time frames are supported by bittrex, is it possible to config this ?

To configure tentacle time frames you should take a look at the tentacle config file : 
tentacles/Evaluator/*TYPE_OF_TENTACLE*/config/*NAME_OF_TENTACLE*.json

**Comment by mrgreedy911** [comment] 2018-10-03 13:18
im using binance now

```
2018-10-03 15:17:23 | ERROR | InstantFluctuationsEvaluator | Exception in eval_impl(): notify_evaluator_thread_managers() got an unexpected keyword argument 'force_TA_refresh'
-- | -- | -- | --

```
just got this error

**Comment by mrgreedy911** [comment] 2018-10-03 13:18
These are the active evalutators
```
{
    "ADXMomentumEvaluator": true,
    "ATRVolatilityEvaluator": false,
    "BBMomentumEvaluator": true,
    "BBTrendEvaluator": false,
    "BTCTalkForumEvaluator": false,
    "CandleAnalysisTrendEvaluator": true,
    "ChaikinOscillatorMomentumEvaluator": false,
    "ChaikinVolatilityEvaluator": false,
    "DMITrendEvaluator": true,
    "DoubleMovingAverageTrendEvaluator": true,
    "EOMTrendEvaluator": false,
    "FullMixedStrategiesEvaluator": true,
    "GoogleTrendStatsEvaluator": true,
    "HighFrequencyStrategiesEvaluator": false,
    "InstantFluctuationsEvaluator": true,
    "InstantMAEvaluator": false,
    "InstantRegulatedMarketEvaluator": false,
    "InstantSocialReactionMixedStrategiesEvaluator": false,
    "InstantVolatilityEvaluator": false,
    "KlingerOscillatorMomentumEvaluator": false,
    "MACDMomentumEvaluator": true,
    "MarketStabilityStrategiesEvaluator": false,
    "MassIndexVolatilityEvaluator": false,
    "MediumNewsEvaluator": false,
    "MoveSignalsStrategyEvaluator": false,
    "OBVMomentumEvaluator": false,
    "RSIMomentumEvaluator": true,
    "RedditForumEvaluator": false,
    "SimpleMixedStrategiesEvaluator": false,
    "StochasticRSIVolatilityEvaluator": false,
    "StochasticVolatilityEvaluator": false,
    "TRIXMomentumEvaluator": false,
    "TwitterNewsEvaluator": false,
    "WhalesOrderBookEvaluator": false,
    "WilliamsRMomentumEvaluator": true
}
```

**Comment by GuillaumeDSM** [comment] 2018-10-03 19:37
Hi mrgreedy911,
For this issue: unexpected keyword argument 'force_TA_refresh', it is already fixed in the dev branch on the source code. 
If you are using the source code directly (not binary versions), switching to the dev branch will solve the problem.
It will also be solved in the next release. 
If you are using a binary version, you can for the moment solve it by replacing the **line 65 of the file tentacles/Evaluator/RealTime/Default/instant_fluctuations_evaluator.py**:
```python
self.notify_evaluator_thread_managers(self.__class__.__name__, force_TA_refresh=True)
```
with
```python
self.notify_evaluator_thread_managers(self.__class__.__name__)
```
Guillaume

**Comment by mrgreedy911** [comment] 2018-10-04 10:48
Ok fixed it
But i got this error now

Exception in eval_impl(): <TimeFrames.THIRTY_MINUTES: '30m'>
--



still on binance

**Comment by mrgreedy911** [comment] 2018-10-04 13:18
Also got these errors today, 
Might be interesting for you guys to see?
Donno how this effects the bot doh?
`2018-10-04 12:51:41	ERROR	DailyTradingModeCreator	Failed to create order : 'NoneType' object is not subscriptable
2018-10-04 13:44:03	ERROR	RESTExchange - binance	Failed to get_price_ticker binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=XVGBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 13:57:44	ERROR	OrdersManager	Error when updating orders
2018-10-04 13:57:44	ERROR	OrdersManager	binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2018-10-04 13:57:47	ERROR	InstantFluctuationsEvaluator	error when refreshing data for LTC/BTC: binance GET https://api.binance.com/api/v1/klines?symbol=LTCBTC&interval=5m&limit=10 HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 14:18:36	ERROR	RESTExchange - binance	Failed to get_price_ticker binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=SCBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 14:18:37	ERROR	OrdersManager	Error when updating orders
2018-10-04 14:18:37	ERROR	OrdersManager	binance GET https://api.binance.com/api/v3/order?timestamp=1538655507741&recvWindow=5000&symbol=QTUMBTC&orderId=36400614&signature=851ea04ae646115adcda247b77162bfdc409d7ac8bb0f8a8b8c8c0597c869e0f HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 14:36:24	ERROR	RESTExchange - binance	Failed to get_price_ticker binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=XVGBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 14:43:31	ERROR	RESTExchange - binance	Failed to get_price_ticker binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=ETHBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 15:00:27	ERROR	RESTExchange - binance	Failed to get_price_ticker binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=ONTBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 15:00:28	ERROR	RESTExchange - binance	Failed to get_price_ticker binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=EOSBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 15:01:21	ERROR	RESTExchange - binance	Failed to get_price_ticker binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=VETBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-10-04 15:10:40	ERROR	RESTExchange - binance	Failed to create order : binance {"code":-2010,"msg":"Account has insufficient balance for requested action."} (order_type: TraderOrderType.BUY_LIMIT, symbol: PPT/ETH, quantity: 0.76, price: 0.014574, stop_price: None)
2018-10-04 15:10:40	ERROR	DailyTradingModeCreator	Failed to create order : 'NoneType' object is not subscriptable`

**Comment by Herklos** [comment] 2018-10-04 13:54
Hello  mrgreedy911,

I can see "Account has insufficient balance for requested action." in your logs.
You should try the bot in simulator mode only [before activate real trading](https://github.com/Drakkar-Software/OctoBot/wiki/Trader).

Secondly, a well known bug on Windows for binance exchange due to a time lag is the cause of this error : "Timestamp for this request is outside of the recvWindow". The solution for this is to try to re-synchronize your computer date.

Thank you again for your feebacks.

**Comment by mrgreedy911** [comment] 2018-10-04 16:48
Ok thank you.
Im trying out the dev build now
im getting 
```
 2018-10-04 18:45:17,675 ERROR    binance              error (Max reconnect retries reached) in web socket all_currencies_prices_callback, calling restart_sockets()
 2018-10-04 18:45:17,973 INFO     binance              2 web socket(s) restarted
 2018-10-04 18:46:07,006 ERROR    binance              error (Max reconnect retries reached) in web socket all_currencies_prices_callback, calling restart_sockets()
 2018-10-04 18:46:07,311 INFO     binance              2 web socket(s) restarted
 2018-10-04 18:46:57,735 ERROR    binance              error (Max reconnect retries reached) in web socket all_currencies_prices_callback, calling restart_sockets()
 2018-10-04 18:46:58,009 INFO     binance              2 web socket(s) restarted
```
after a while

**Comment by GuillaumeDSM** [comment] 2018-10-04 18:20
If you are watching the Bitcoin cash currency, this problem is due to binance having it listed as bcc instead of bch. REST interface makes the conversion into bcc but websocket interface doesn't. it's solved already in the dev branch and will be released very soon. 

Thanks for using OctoBot !

**Comment by Herklos** [comment] 2018-10-04 18:39
You can follow the new release progress [here](#419).

**Comment by Herklos** [comment] 2018-12-12 15:18
Fix with https://github.com/Drakkar-Software/OctoBot/pull/419 merge.

**Closed by Herklos** 2018-12-12 15:18 UTC
Labels: user issue
