### ISSUE TITLE
Incorrect display of portfolio in telegram response

### ISSUE THREAD

**Issue by VictorStatko** [Drakkar-Software/OctoBot#2338] opened 2023-05-12 17:07 UTC
## Describe your environment
  * OctoBot instance 0.4.49 running in docker (using docker compose)
 
## Describe the problem:
**Describe the bug**
I receive some strange data in response of /portfolio command in telegram.

Can be compered with web version.

![Selection_554](https://github.com/Drakkar-Software/OctoBot/assets/34319599/d0ca9c5c-5c3e-414b-bcdf-e6ca27cfa2a7)

![Selection_556](https://github.com/Drakkar-Software/OctoBot/assets/34319599/c17544f3-c49b-4d5f-b180-e43a35289f6a)

**Expected behavior**
Telegram response and web data should be the same.

**Comment by GuillaumeDSM** [comment] 2023-05-13 08:55
Thanks @VictorStatko !
It will be fixed by https://github.com/Drakkar-Software/OctoBot/issues/2338 and included in OctoBot 0.4.51.
For now the web interface value is right and on the telegram interface, the issue is that each asset's value is multiplied by the number of times it's appearing on your enabled exchanges.

**Closed** 2023-05-13 09:37 UTC
